version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "33000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WeatherDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - network-app
      - db-network
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  meteo-server:
    depends_on:
      - mysql
    build:
      ./src
    restart:
      "always"
    ports:
      - "6000:6000"
    networks:
      - network-app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network


volumes:
  db_data:
    name: db_data

networks:
  network-app:
    name: network-app
  db-network:
    name: db-network
